### ISSUE TITLE
WebSocket?

### ISSUE THREAD

**Issue by stumpyfr** [edmund-huber/ergonomadic#11]
Wanted to know if you have some plan to support WebSocket?
I am looking for a good solution for my chat system but I must keep IRC protocol.

After few looks at your code...I start to think the workload would not be major, if you confirm I can maybe try to work on that.

**Comment by stumpyfr** [comment]
title

**Comment by edmund-huber** [comment]
Sounds reasonable, that sounds like something useful.

That being said, have you tried using something like https://github.com/kanaka/websockify to build a bridge between WS and plain old TCP? That might save you time.

**Comment by stumpyfr** [comment]
Yep I look about it but for a production system, add a daemon just to bridge is rarely a good idea.
I will try to get sometime to work on that :)

**Comment by stumpyfr** [comment]
First version in #12

**Comment by edmund-huber** [comment]
https://github.com/edmund-huber/ergonomadic/pull/14
