### ISSUE TITLE
Opening up some of the code

### ISSUE THREAD

**Issue by wjzijderveld** [edmund-huber/ergonomadic#18]
Would you be interested in opening up some of the internal API you use?

In particular I would like to have access to [some of the channels](https://github.com/edmund-huber/ergonomadic/blob/efce628c875e8bdff8de109999a796f57b28c562/irc/server.go#L165-L183).

My use case: I'm trying to build a proxy between Hipchat and IRC. I just hate the Hipchat client and really like WeeChat :smile:, so I want to have a proxy in between.
It might grow into something more generic like an XMPP - IRC proxy. 

But with the current implementation I'm unable to use this project. But I'm reluctant to build the whole IRC server part myself. 

I can understand if you are not willing to do it, as this project is meant for end-users and maintaining an API is something different.

**Comment by edmund-huber** [comment]
I'm open to any ideas. :) Anything that make the core IRC protocol -handling code more useful (splitting into a library?) would be neat.

That said, have you tried [bitlbee](https://www.bitlbee.org)? It's an IRC server that provides an interface to other chat networks and protocols.

**Comment by wjzijderveld** [comment]
Nice :-) 

I have tried bitlbee a while back, didn't like it a lot :-) But maybe I should give it another chance first..

**Comment by edmund-huber** [comment]
Closing until we can think of something concrete to do.

**Comment by wjzijderveld** [comment]
Hi again :-)

Just found this package: https://github.com/sorcix/irc
Might be useful for you (it is for me).
