### ISSUE TITLE
/topic causes mIRC client to disconnect from server

### ISSUE THREAD

**Issue by nxths** [edmund-huber/ergonomadic#23]
Issuing a /topic command in mIRC 7.43 causes my client to disconnect and then reconnect to the connected server after 10-20s.  Not sure if my client is receiving any messages from the server inbetween the /topic and the disconnect

**Comment by nxths** [comment]
Hmm interestingly attempting to change the topic (/topic foo) causes the server to send back the topic as though I passed in the command w/ no argument (/topic)

**Comment by DanielOaks** [comment]
This is caused because `/topic` sends just `TOPIC` to the server, which is a malformed command. That causes the server to stop accepting any commands from the client (including `PING`/`PONG`), which is what's causing this issue. Fixed by #32

**Comment by nxths** [comment]
Oh nice thanks for figuring this out + fix
