### ISSUE TITLE
Docker image and automated builds

### ISSUE THREAD

**Issue by prologic** [edmund-huber/ergonomadic#33]
Would you be willing to accept a PR for a `Dockerfile` so we can publish automated builds of this thing? I'd like to try out your [ergonomadic](https://github.com/edmund-huber/ergonomadic)

**Comment by edmund-huber** [comment]
Absolutely.

**Comment by prologic** [comment]
So I have some local commits that get this going but ran into an issue:

```#!bash
Removing intermediate container 38428b75ca94
Step 12/12 : RUN go install -v
 ---> Running in 2d20e8283a6d
github.com/docopt/docopt-go
github.com/gorilla/websocket
golang.org/x/net/context
github.com/mattn/go-sqlite3
# github.com/mattn/go-sqlite3
exec: "gcc": executable file not found in $PATH
golang.org/x/crypto/blowfish
golang.org/x/crypto/bcrypt
golang.org/x/text/transform
golang.org/x/text/unicode/norm
gopkg.in/yaml.v2
golang.org/x/crypto/ssh/terminal
The command '/bin/sh -c go install -v' returned a non-zero code: 2
```

Any objections to swapping out SQLite for something more Go native like BoltDB? Do we really need a relationship database to store state here

**Comment by edmund-huber** [comment]
Let's first get the Docker build going, then we can change to BoltDB or whatever makes sense. It looks like you just need to `apt-get build-essentials` for gcc.

**Comment by prologic** [comment]
I'm using the ever popular and smaller [alpine](https://hub.docker.com/_/alpine/) as a base image but yeah effectively the same (*install gcc*) -- Okay I'l do that for now and put the PR up and then we can identify whether SQLite is really the best choice here (*in a separate issue*)
