### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by prologic** [edmund-huber/ergonomadic#44]
@edmund-huber I noticed you closed and did not merge all of my PRs.

If your intention is to close/discontinue this project I want to rebrand it based on your codebase.

Do you wish for you to retain your name in the LICENSE as the previous author/maintainer of the original codebase or are you happy to let me diverge the codebase entirely?

**Comment by edmund-huber** [comment]
Yes, sorry, I realized that I don't have the time to really work on ergonomadic. Please fork if you would like. An attribution to myself and Jeremy Latt as previous maintainers, somewhere in files, would be very appreciated.

**Comment by prologic** [comment]
Depreciated project.
